import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProvider } from "./appContent";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // optional CSS variable
});

export const metadata: Metadata = {
  title: "Gridkey",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${inter.variable} font-[inter] overflow-x-hidden`}>
        <div id="app-root" className="min-h-screen w-full">
          <AppProvider>
            <Navbar />
            {children}
            <Footer />
          </AppProvider>
        </div>
      </body>
    </html>
  );
}
